### ISSUE TITLE
ss搜索结果中文乱码

### ISSUE THREAD

**Issue by wanghaocun** [okibcn/ss#2]
![image](https://user-images.githubusercontent.com/25606300/221742322-9e9f0be4-658b-4f0c-a2ea-a32c8b818362.png)

**Comment by okibcn** [comment]
Chinese shows up perfectly in the windows terminal :
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/22417711/221744592-31109b58-5b8c-4ef5-a86a-835acdb136d8.png">

And even in the old windows console:
<img width="959" alt="image" src="https://user-images.githubusercontent.com/22417711/221745277-ef9997fb-39a2-401c-bce8-9e989e1f4a8e.png">

Can you please provide more detail about your system? For instance 
- The output of: `$PSVersionTable` in powershell,
- The terminal application you are using
- the shell and intermediate shells you are using (cmd.exe, pwsh.exe, powershell.exe)

**Comment by wanghaocun** [comment]
![image](https://user-images.githubusercontent.com/25606300/221747136-b7c6b6d3-f273-4b69-bbf9-c753d8e8e652.png)

Here is my configuration:
- PowerShell 7.3.2
- Windows Terminal Version: 1.16.230126001
- shell: pwsh.exe

**Comment by wanghaocun** [comment]
`code $PROFILE`:
![image](https://user-images.githubusercontent.com/25606300/221747779-9086a0ed-f02f-45ea-87e2-f81723778ddf.png)

`Windows Terminal Font`:
![image](https://user-images.githubusercontent.com/25606300/221747898-7f1edf48-2e70-43e7-bce8-541b219ec685.png)

**Comment by okibcn** [comment]
I don't see any out of normal there. Windows 10 should handle properly the UFT-8 characters.

One of the manifests not showing properly in your system is: `https://raw.githubusercontent.com/DoveBoy/Apps/master/bucket/qq.json`

Try typing this command in your terminal:
```pwsh
(iwr https://raw.githubusercontent.com/DoveBoy/Apps/master/bucket/qq.json).content
```
It should return this:
![image](https://user-images.githubusercontent.com/22417711/221749430-60cc951c-2036-4a44-b567-12411cc6273b.png)

Is this properly displayed in your system?

**Comment by wanghaocun** [comment]
Yes, it does:

![image](https://user-images.githubusercontent.com/25606300/221749758-b26f54e4-2150-4857-8ee6-96cdb58b5ddb.png)

**Comment by okibcn** [comment]
I will do some tests here.

**Comment by okibcn** [comment]
Can you please tell me whether this:
```pwsh
7z e -so $env:TEMP/AllAppsDB.7z | sls '^"qq"'
```
returns this:
<img width="937" alt="image" src="https://user-images.githubusercontent.com/22417711/221757147-8927ace4-fef1-4246-b79e-93628aa14fa2.png">

**Comment by wanghaocun** [comment]
> 👇 

![image](https://user-images.githubusercontent.com/25606300/221816596-ab2f6f36-6dc9-4173-86c9-967baf9a1279.png)

**Comment by wanghaocun** [comment]
Sorry for the late reply:

1.
![image](https://user-images.githubusercontent.com/25606300/221817303-6aaffeb2-92fd-4376-a283-65f379dca452.png)

2.
![image](https://user-images.githubusercontent.com/25606300/221817452-89fc2cf6-867b-4ce4-b7e7-5e6ad2b547fc.png)

3.
![image](https://user-images.githubusercontent.com/25606300/221817578-7df27ff2-ae37-4cc7-a70e-74105e76a222.png)

**Comment by okibcn** [comment]
Thanks. I see your system fails in the first part. I will double-check the database again today, but yesterday I saw that it has the same bytes (same encoding) as the original JSON (which renders fine in your system). So, the problem might be in the Select-Content (sls) Powershell CmdLet, leading to a clear configuration problem in your system.

**Comment by okibcn** [comment]
Let's do some quick tests:
This works in your system as you showed in your previous [comment](https://github.com/okibcn/ss/issues/2#issuecomment-1447537137):
```pwsh
(iwr https://raw.githubusercontent.com/DoveBoy/Apps/master/bucket/qq.json).content
```

So I need to know the output of these tests:
Download this [miniDB.csv](https://github.com/okibcn/ss/files/10855174/miniDB.csv) file to the current folder:
```pwsh
iwr https://github.com/okibcn/ss/files/10855174/miniDB.csv -OutFile miniDB.csv
```
This file has the same byte encoding as the large database and the original manifest file, UTF-8 for Chinese Unicode characters. You can check that by uploading the json file and this miniDB file to www.hexed.it or any CLI utility such as hexyl (you can get it from Scoop). The byte string in offset 0x85 in miniDB file should match offset 0x44 in qq.json file. The hex values for that byte string is:
```hex
e6 af 8f - e4 b8 80 - e5 a4 a9 - ef bc 8c - e4 b9 90 - e5 9c a8 - e6  b2 9f - e9 80 9a
```


Now let's do a couple of tests:
1. What is the output when typing this?:
```pwsh
Get-Content miniDB.csv
```

It should return:
<img width="521" alt="image" src="https://user-images.githubusercontent.com/22417711/221994662-f01a5f3e-92cb-41f9-bc4c-f5ab0439793a.png">

2. If I am right this test will fail in your system:
```pwsh
Get-Content miniDB.csv | Select-String qq
```
But this should return this:
<img width="527" alt="image" src="https://user-images.githubusercontent.com/22417711/221995447-9d90263f-6eac-4062-9551-f6facc7ed9bf.png">

Now let's test a couple of workarounds:
3. First solution candidate:
```pwsh
Get-Content miniDB.csv  | Select-String qq -Encoding utf8NoBOM
```
4. Alternate solution:
```pwsh
$PSDefaultParameterValues = @{ '*:Encoding' = 'utf8' }
Get-Content miniDB.csv | Select-String qq
```

If these tests are not solving the issue, then your problem is the outdated OS. Then it would be time to test [this solution](https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window/57134096#57134096).

**Comment by wanghaocun** [comment]
Below is the test result, please check:

![image](https://user-images.githubusercontent.com/25606300/222022707-449aae88-fe97-44f2-af42-ba88c9ff1b47.png)

BTW:
OS version: `Windows 10 IoT Enterprise LTSC 2021 (x64) (Chinese-Simplified)`
Version Number: `21H2`

**Comment by okibcn** [comment]
hmmm.... There is something I can't understand. 
```posh
7z e -so $env:TEMP/AllAppsDB.7z | sls '^"qq"'
```
was [failing](https://github.com/okibcn/ss/issues/2#issuecomment-1447884161) in your system, but
```posh
Get-Content miniDB.csv | Select-String qq
```
was working fine?

Can you please double check these last two tests?

**Comment by wanghaocun** [comment]
Yes, I'm just as confused as you are. 
Double check these last two tests:

![image](https://user-images.githubusercontent.com/25606300/222029949-85cd7753-0343-4455-82d2-34364117a86a.png)

**Comment by okibcn** [comment]
Ok, let's see if the problem is the pipe output of 7Z vs the pipe output of Get-Content (gc):

Next tests:
1. 7z pipe out test:
```posh
7z e -so $env:TEMP/AllAppsDB.7z > db1.csv
gc db1.csv | select-string "I'm QQ"
```
2. 7z writing output to file:
```posh
7z e $env:TEMP/AllAppsDB.7z
gc .\AllAppsDB.csv | select-string "I'm QQ"
```
In both cases the output should be the same:
<img width="590" alt="image" src="https://user-images.githubusercontent.com/22417711/222031327-8ae8ac96-2c3d-42de-af26-c6d7a4eae78b.png">



Don't forget to cleanup later the large csv files with 
```posh
ri db1.csv,AllAppsDB.csv
```

**Comment by wanghaocun** [comment]
I have a different output here:

![image](https://user-images.githubusercontent.com/25606300/222031814-04fe04d9-2256-4e62-aa1b-cc5f6e92942d.png)

**Comment by okibcn** [comment]
We are getting closer.
Try this:
1. step by step:
```posh
$PSDefaultParameterValues = @{ '*:Encoding' = 'utf8' }
7z e -so $env:TEMP/AllAppsDB.7z > db1.csv
gc db1.csv | select-string "I'm QQ"
```

2. in a pipe:
```posh
$PSDefaultParameterValues = @{ '*:Encoding' = 'utf8' }
7z e -so $env:TEMP/AllAppsDB.7z | select-string "I'm QQ"
```

**Comment by wanghaocun** [comment]
Yeah. Here are the steps:

![image](https://user-images.githubusercontent.com/25606300/222033014-5116dd43-a2fb-4e8e-9b3a-3149f3a9d670.png)

**Comment by okibcn** [comment]
I have this on top of my $PROFILE to ensure UTF-8 is used both in output and input:
```posh
[console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding
```

So do this:
```posh
[console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding
7z e -so $env:TEMP/AllAppsDB.7z | select-string "I'm QQ"
```

**Comment by wanghaocun** [comment]
That output normally:

![image](https://user-images.githubusercontent.com/25606300/222034492-7da8791e-9c92-43ff-ab81-165f946eaa2a.png)

**Comment by okibcn** [comment]
Well, we found your issue. For some reason, your system doesn't default to UTF-8 input. Powershell Core defaults to UTF-8 encoding. There must be something in your $ PROFILE getting it wrong.
Please attach your $PROFILE following the instructions I provided above. You can retrieve it easily with:
```posh
cp $PROFILE ./myprofile.ps1
```
Just upload `myprofile.ps1` file to your reply here.

If it isn't long you can just copy and paste it in the message body.

**Comment by wanghaocun** [comment]
> That output normally:
> 
> ![image](https://user-images.githubusercontent.com/25606300/222034492-7da8791e-9c92-43ff-ab81-165f946eaa2a.png)

Thus, ss also output normally:

![image](https://user-images.githubusercontent.com/25606300/222035137-230515a8-d08e-4396-bc78-1488fe24036d.png)

**Comment by wanghaocun** [comment]
> Well, we found your issue. For some reason, your system doesn't default to UTF-8 input. Powershell Core defaults to UTF-8 encoding. There must be something in your $ PROFILE getting it wrong. Please attach your $PROFILE following the instructions I provided above. You can retrieve it easily with:
> 
> ```powershell
> cp $PROFILE ./myprofile.ps1
> ```
> 
> Just upload `myprofile.ps1` file to your reply here.
> 
> If it isn't long you can just copy and paste it in the message body.

This is my profile:

```powershell
# pwsh7 profile #

# set scoop-search
Invoke-Expression (&scoop-search --hook)
# set oh-my-posh
oh-my-posh init pwsh --config "$env:POSH_THEMES_PATH/multiverse-neon.omp.json" | Invoke-Expression
```

**Comment by okibcn** [comment]
OK, add the line
```posh
[console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding
```
 on top of your profile, and that's all you need to do.

You can edit your profile easily with
```posh
notepad $PROFILE
```

Fixed!

**Comment by wanghaocun** [comment]
> OK, add the line
> 
> ```powershell
> [console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding
> ```
> 
> on top of your profile, and that's all you need to do.
> 
> Fixed!

Yes, I've tested it and it works perfectly!
Thanks very mush!
So, the issue is `myprofile` problem, not the `ss` problem.
Best regards!
